#!/bin/bash

# can we create the equivalent of the following line?
#node das2json.mjs <neva-sample.drawio >1.json

# create temporary kill-file, containing only "string"s
./rewrite kill.ohm kill.rewrite <kill-file >tmp

# brute-force conversion of neva-sample.drawio to 1.json
./ndsl drawio.ohm drawio.rewrite support.js <neva-sample.drawio >1.json

# expand all style="...;...;" to separate JSON members
./rewrite styleexpand.ohm styleexpand.rewrite <1.json >2.json

# delete all noise members that pertain only to graphical information
sed -f tmp <2.json >3.json

# rewrite all geometry members to form "boundingBox" : [x,y,w,h],
./rewrite geometry.ohm geometry.rewrite <3.json >4.json

# rewrite "vertex" : 1, to "shape" : "vertex",
sed -e 's/"vertex"[ ]*:[ ]*1,/"shape" : "vertex",/g' <4.json  >5.json

# figure out parts and ports, leave connections for next pass
#./rewrite parts.ohm identity-parts.rewrite <5.json | sed -e '/^[ \t]*$/d' >6.json
./rewrite parts.ohm parts.rewrite <5.json >6.json

# gather symbol table that maps ID to KIND, then emit everything as-is, preceded by the symbol table itself, a fresh symbol table for each diagram
./rewrite gather.ohm gather.rewrite <6.json >7.json

# rewrite every connection adding directions, based on info in symbol table
./rewrite direction.ohm direction.rewrite <7.json >8.json

# examine the array 'root', keep only items that match { "kind" : ("inputgate" | "inputport" | "outputgate" | "outputport" | "part" | "wire") ... }
./rewrite keep.ohm keep.rewrite <8.json | ./make-readable

